// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeasIFsRoD_1SoloZD_lSpy7j6rbyCjzQ',
    appId: '1:950605811460:web:26a47ab173d78c56f50a51',
    messagingSenderId: '950605811460',
    projectId: 'ringkaspos',
    authDomain: 'ringkaspos.firebaseapp.com',
    storageBucket: 'ringkaspos.firebasestorage.app',
    measurementId: 'G-V0CEPMS3F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-B01PRXL11O1XzrgRZumUNcyKUKZmhA',
    appId: '1:950605811460:android:feffab00934e57acf50a51',
    messagingSenderId: '950605811460',
    projectId: 'ringkaspos',
    storageBucket: 'ringkaspos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAea9mkOB21JtFIXKgLOeWw3M3uI1MVkb0',
    appId: '1:950605811460:ios:480495bf1208fce4f50a51',
    messagingSenderId: '950605811460',
    projectId: 'ringkaspos',
    storageBucket: 'ringkaspos.firebasestorage.app',
    iosBundleId: 'com.ringkas.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAea9mkOB21JtFIXKgLOeWw3M3uI1MVkb0',
    appId: '1:950605811460:ios:495193f363ab3954f50a51',
    messagingSenderId: '950605811460',
    projectId: 'ringkaspos',
    storageBucket: 'ringkaspos.firebasestorage.app',
    iosBundleId: 'com.example.flutterPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeasIFsRoD_1SoloZD_lSpy7j6rbyCjzQ',
    appId: '1:950605811460:web:ba9cdaa4236c4ae9f50a51',
    messagingSenderId: '950605811460',
    projectId: 'ringkaspos',
    authDomain: 'ringkaspos.firebaseapp.com',
    storageBucket: 'ringkaspos.firebasestorage.app',
    measurementId: 'G-D1J8R3JC71',
  );

}