// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGzaj1hzVWZJJZzf6TfrDqBRSKyaqLshY',
    appId: '1:270816365340:web:70f408f100fc5e245b08d9',
    messagingSenderId: '270816365340',
    projectId: 'marketplacemandiri',
    authDomain: 'marketplacemandiri.firebaseapp.com',
    databaseURL: 'https://marketplacemandiri-default-rtdb.firebaseio.com',
    storageBucket: 'marketplacemandiri.firebasestorage.app',
    measurementId: 'G-9PYYZLCCJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASZN1gi_4aGiOsuIzplQYZr8bdOai6QFw',
    appId: '1:270816365340:android:0ae6f7332aea9a165b08d9',
    messagingSenderId: '270816365340',
    projectId: 'marketplacemandiri',
    databaseURL: 'https://marketplacemandiri-default-rtdb.firebaseio.com',
    storageBucket: 'marketplacemandiri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFExiQ0BwS7D3yyzZbsBTdjqwS7LS5g_o',
    appId: '1:270816365340:ios:591c3ac1cce316b35b08d9',
    messagingSenderId: '270816365340',
    projectId: 'marketplacemandiri',
    databaseURL: 'https://marketplacemandiri-default-rtdb.firebaseio.com',
    storageBucket: 'marketplacemandiri.firebasestorage.app',
    iosBundleId: 'com.ringkaspos.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFExiQ0BwS7D3yyzZbsBTdjqwS7LS5g_o',
    appId: '1:270816365340:ios:14cc45d710395a935b08d9',
    messagingSenderId: '270816365340',
    projectId: 'marketplacemandiri',
    databaseURL: 'https://marketplacemandiri-default-rtdb.firebaseio.com',
    storageBucket: 'marketplacemandiri.firebasestorage.app',
    iosBundleId: 'com.example.flutterPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGzaj1hzVWZJJZzf6TfrDqBRSKyaqLshY',
    appId: '1:270816365340:web:70f408f100fc5e245b08d9',
    messagingSenderId: '270816365340',
    projectId: 'marketplacemandiri',
    authDomain: 'marketplacemandiri.firebaseapp.com',
    databaseURL: 'https://marketplacemandiri-default-rtdb.firebaseio.com',
    storageBucket: 'marketplacemandiri.firebasestorage.app',
    measurementId: 'G-9PYYZLCCJT',
  );

}